import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/layout/Footer'
import Navbar from '../components/layout/Navbar'
import Client from '../components/sections/Client'
import GetCozy from '../components/sections/GetCozy'
import Herosection from '../components/sections/Herosection'
import styles from '../styles/Home.module.css'
import VideoDemo from '../components/sections/VideoDemo'
import Testimonials from '../components/sections/Testimonials'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Herosection />
      <GetCozy />
      <Testimonials />
      
      <Client />
      <VideoDemo />
      <Footer />

     

      
    </div>
  )
}
